version: '3.6'
services:
  ninvt_express:
    network_mode: host
    container_name: ninvt_express
    build:
      dockerfile: express.dockerfile
      context: .
      args:
        - EXPRESS_PORT=${EXPRESS_PORT}
        - NODE_ENV=${NODE_ENV}
    volumes:
      -  ${PWD}:/apps
    restart: always
    environment:
      - EXPRESS_PORT=${EXPRESS_PORT}
      - NODE_ENV=${NODE_ENV}
  ninvt_graphql_engine:
    container_name: ninvt_graphql_engine
    network_mode: host
    image: hasura/graphql-engine:v1.3.3
    restart: always
    depends_on:
      - "ninvt_express"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${POSTGRES_URI}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      # HASURA_GRAPHQL_JWT_SECRET: ${HASURA_GRAPHQL_JWT_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
      HASURA_GRAPHQL_SERVER_PORT: ${HASURA_GRAPHQL_SERVER_PORT}
      # HASURA_ACTION_SECRET: ${HASURA_ACTION_SECRET}
      HASURA_GRAPHQL_DEV_MODE: "true"
      ACTION_BASE_URL: ${ACTION_BASE_URL}

    
    